name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  API__TOKEN: token
  DATABASE__URL: file:///tmp/db.sqlite

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Set up database
        run: bun run db:migrate
      - name: Run integration tests
        run: bun run test
